### ISSUE TITLE
How to open link in new tab

### ISSUE THREAD

**Issue by aakhan89** [trendmicro-frontend/react-sidenav#31]
As `**NavItem**` has `div` element so we can not open link in new tab, is there anyway to convert `div` element to `a` 

also I have tried `**componentClass='a'**` but it's not working fine...!

![image](https://user-images.githubusercontent.com/38126236/61768091-c3843d00-adff-11e9-85a3-f8118ab627e4.png)

**Comment by aakhan89** [comment]
@cheton can you please help out ?

**Comment by alexandrtovmach** [comment]
@aakhan89 Hey, I faced with the same question. My solution, probably it's help.

```js
<NavItem
	eventKey={menuItem.url}
	className="new-sidebar-item"
>
	<NavIcon>
		/**
		 * <Link /> component from 'react-router-dom'.
		 * Feel free to use default <a> tag
		 */
		<Link to={menuItem.url}>
			<FontAwesomeIcon icon={menuItem.icon} />
		</Link>
	</NavIcon>
	<NavText>
		<Link to={menuItem.url}>
			{menuItem.label}
		</Link>
	</NavText>
</NavItem>
```
Styles for it:
```css
.new-sidebar-item {
	a {
		display: block;
		width: 100%;
		height: 100%;
		text-decoration: none;
	}
}
```
